/* akuji_trace.js - GENERATED by tools/make_trace.py. Do not edit by hand.
 *
 * Groups: frame state load   (26 functions)
 *
 * Traces the ORIGINAL akuji.exe while it actually runs, which is the one thing
 * reading it cannot do. Addresses come from notes/game_functions.txt, the
 * project's address authority, so a wrong address here would have to be wrong
 * there too.
 *
 *   cd "<gamedir>"
 *   frida -f akuji.exe -l akuji_trace.js
 *
 * Output goes to akuji_trace.log beside the exe.
 *
 * READ THE LOG AS A SEQUENCE, NOT A TRANSCRIPT. Entry is logged, not exit, so
 * nesting is implied by order rather than shown. That is deliberate: logging
 * both doubles the volume, and what the open questions need is which functions
 * run, in what order, and with what state - not how long each took.
 */

'use strict';

var IMAGE_BASE = ptr(0x400000);       /* the PE's preferred base */
var MAX_LINES = 400000;               /* a cap, so a long session cannot fill
                                         the disk unnoticed */

var FUNCS = [
  [0x456038, "MessageBox_Update"],
  [0x456698, "PowerUp_Show"],
  [0x4568d0, "Overlay_Update"],
  [0x461a44, "GameOver_Update"],
  [0x461ee4, "PauseMenu_Update"],
  [0x46214c, "Title_Init"],
  [0x462210, "Stage_Begin"],
  [0x462330, "Title_MainMenu"],
  [0x462f40, "Game_StartOrLoad"],
  [0x463154, "Opening_Update"],
  [0x463624, "Ending_Update"],
  [0x464484, "Ending_ShowPicture"],
  [0x4645b0, "Terrain_Configure"],
  [0x464d30, "TFrm_main_AppIdle"],
  [0x4653c8, "GameState_Reset"],
  [0x465584, "TFrm_main_DDDD1Init"],
  [0x465a1c, "Load_Stage_Assets"],
  [0x465b50, "Load_Event_Scripts"],
  [0x465e9c, "Load_Surface_Textures"],
  [0x4660b8, "Load_Sprite_Sheets"],
  [0x466340, "Load_Map"],
  [0x466644, "TFrm_main_FormDestroy"],
  [0x4669f8, "Load_StageTable"],
  [0x466c78, "Display_SetFullScreen"],
  [0x466dfc, "Sounds_LoadAll"],
  [0x46716c, "entry"]
];

var GLOBALS = [
  [0x46d06c, "gameState"],
  [0x46cbbc, "savedState"],
  [0x46cc14, "screenPhase"],
  [0x46d174, "screenTimer"],
  [0x46d298, "screenStep"],
  [0x46cef8, "titleSubMode"],
  [0x46cf88, "menuIndex"],
  [0x46e040, "randSeed"]
];

function findModule() {
    /* mainModule is the reliable one under -f; the others are fallbacks for
     * attaching to an already-running game by name or pid. */
    try {
        if (Process.mainModule) { return Process.mainModule; }
    } catch (e) { /* fall through */ }
    var m = null;
    try { m = Process.findModuleByName('akuji.exe'); } catch (e) { m = null; }
    if (m) { return m; }
    var mods = Process.enumerateModules();
    for (var i = 0; i < mods.length; i++) {
        if (mods[i].name.toLowerCase().indexOf('akuji') !== -1) {
            return mods[i];
        }
    }
    return null;
}

var mod = findModule();
if (mod === null) {
    console.log('akuji_trace: could not find the akuji module - nothing hooked');
} else {

/* Everything is read through the slide rather than at the literal address, so
 * this works whether or not the image loads at its preferred base. */
var slide = mod.base.sub(IMAGE_BASE);

/* akuji.exe is a 32-bit PE, so the registers below are the 32-bit names. If
 * this ever runs somewhere else the field names would be wrong and the log
 * would be silently useless, so say so rather than produce one. */
if (Process.arch !== 'ia32') {
    console.log('akuji_trace: expected a 32-bit process, got ' + Process.arch +
                ' - the register names below would be wrong; not hooking');
    throw new Error('wrong architecture');
}

/* Beside the exe, not in the CWD: under -f the working directory is whatever
 * the spawn inherited, and a log that lands somewhere unpredictable is a log
 * nobody finds. */
var logPath = 'akuji_trace.log';
try {
    /* No backslash literal here on purpose: this string travels
     * through a Python template, and counting escape layers is how
     * the last three versions of this line came out wrong. */
    var BS = String.fromCharCode(92);
    var sep = mod.path.lastIndexOf(BS);
    if (sep < 0) { sep = mod.path.lastIndexOf('/'); }
    if (sep > 0) { logPath = mod.path.substring(0, sep + 1) + 'akuji_trace.log'; }
} catch (e) { /* keep the relative fallback */ }
var log = new File(logPath, 'w');
var nLines = 0;
var frame = 0;
var capped = false;

function emit(s) {
    if (capped) { return; }
    if (nLines >= MAX_LINES) {
        log.write('--- capped at ' + MAX_LINES + ' lines ---\n');
        log.flush();
        capped = true;
        return;
    }
    nLines++;
    log.write(s + '\n');
    if ((nLines & 0x3ff) === 0) { log.flush(); }
}

/* Zero-valued globals are omitted, so a name APPEARING in the log is itself
 * the signal that something left zero - which is what makes a phase change
 * visible without diffing every line.
 *
 * Some of these cells hold a POINTER to the variable rather than the variable
 * (see the note in make_trace.py). Anything that looks like a pointer into the
 * image's data range is followed and reported as `name*=`, so the log shows
 * both and never silently reports an address as though it were a value. */
var DATA_LO = 0x460000, DATA_HI = 0x4A0000;

function globalsText() {
    var parts = [];
    for (var i = 0; i < GLOBALS.length; i++) {
        var name = GLOBALS[i][1];
        var v = null;
        try { v = slide.add(GLOBALS[i][0]).readS32(); } catch (e) { v = null; }
        if (v === null || v === 0) { continue; }
        var looksPtr = (v >= DATA_LO && v < DATA_HI);
        if (looksPtr) {
            var d = null;
            try { d = ptr(v).readS32(); } catch (e) { d = null; }
            if (d !== null) {
                parts.push(name + '*=' + d);
                continue;
            }
        }
        parts.push(name + '=' + v);
    }
    return parts.join(' ');
}

emit('# akuji_trace  base=' + mod.base + ' slide=' + slide);
emit('# groups: frame state load');
emit('# columns: frame  function  eax edx ecx [stack0,stack1]  | globals');
emit('# a global at zero is omitted, so a name appearing IS the change');

for (var i = 0; i < FUNCS.length; i++) {
    (function (addr, name) {
        var isFrame = (name === 'TFrm_main_AppIdle');
        try {
            Interceptor.attach(slide.add(addr), {
                onEnter: function () {
                    var c = this.context;
                    if (isFrame) {
                        frame++;
                        /* The frame marker is what lets two logs be lined up.
                         * Without it a diff drifts by one call and never
                         * recovers. */
                        emit('--- frame ' + frame + ' --- ' + globalsText());
                        return;
                    }
                    var stk = '';
                    try {
                        stk = ' [' + c.esp.add(4).readS32() + ',' +
                                     c.esp.add(8).readS32() + ']';
                    } catch (e) { stk = ''; }
                    emit(frame + '  ' + name +
                         '  ' + c.eax.toInt32() +
                         ' ' + c.edx.toInt32() +
                         ' ' + c.ecx.toInt32() + stk +
                         '  | ' + globalsText());
                }
            });
        } catch (e) {
            console.log('akuji_trace: could not hook ' + name + ' @ 0x' +
                        addr.toString(16) + ': ' + e.message);
        }
    })(FUNCS[i][0], FUNCS[i][1]);
}

console.log('akuji_trace: base ' + mod.base + ', ' + FUNCS.length +
            ' hooks, writing ' + logPath);

rpc.exports = {
    flush: function () { log.flush(); return nLines; },
    lines: function () { return nLines; }
};

}
